model_path: assets/models/gb_model.pkl
feature_selection_k: 8
model_params:
  n_estimators: 200
  learning_rate: 0.1
  max_depth: 5
  min_samples_split: 50
  min_samples_leaf: 20
  subsample: 0.8
  random_state: 42
grid_search_params:
  model__n_estimators: [100, 200]
  model__learning_rate: [0.05, 0.1]
  model__max_depth: [3, 5] 